# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\a'su's\Desktop\自然语言处理\Qt\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(948, 648)
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 821, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.traditonal_button = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.traditonal_button.setFont(font)
        self.traditonal_button.setIconSize(QtCore.QSize(60, 60))
        self.traditonal_button.setObjectName("traditonal_button")
        self.verticalLayout.addWidget(self.traditonal_button)
        self.cnn_button = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget)
        self.cnn_button.setEnabled(True)
        self.cnn_button.setMinimumSize(QtCore.QSize(0, 150))
        self.cnn_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.cnn_button.setFont(font)
        self.cnn_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cnn_button.setIconSize(QtCore.QSize(60, 60))
        self.cnn_button.setObjectName("cnn_button")
        self.verticalLayout.addWidget(self.cnn_button, 0, QtCore.Qt.AlignVCenter)
        WelcomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WelcomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 948, 30))
        self.menubar.setObjectName("menubar")
        WelcomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WelcomeWindow)
        self.statusbar.setObjectName("statusbar")
        WelcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "欢迎界面"))
        self.label.setText(_translate("WelcomeWindow", "欢迎使用英文单词纠错器"))
        self.traditonal_button.setText(_translate("WelcomeWindow", "Traditional Method"))
        self.cnn_button.setText(_translate("WelcomeWindow", "Seq2Seq"))
