"""empty message

Revision ID: 5a0106903f4b
Revises: d72c5a28e2d8
Create Date: 2022-12-12 15:36:45.872011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a0106903f4b'
down_revision = 'd72c5a28e2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
