"""empty message

Revision ID: a8c2eae5bfd9
Revises: 53e2a525d65d
Create Date: 2022-12-12 15:31:43.272464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c2eae5bfd9'
down_revision = '53e2a525d65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'about_me',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'about_me',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
