#include "stepmotor.h"
#include "delay.h"

void STEP_MOTOR_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB | RCC_APB2Periph_GPIOC,ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO,ENABLE);
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Pin = STEP_MOTOR_A | STEP_MOTOR_B | STEP_MOTOR_C | STEP_MOTOR_D;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(STEP_MOTOR_PORT,&GPIO_InitStructure);
	//禁用JTAG
	GPIO_PinRemapConfig(GPIO_Remap_SWJ_Disable,ENABLE);
	STEP_MOTOR_OFF();//低电平，初始为关继电器
}
void STEP_MOTOR_OFF(void)
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B | STEP_MOTOR_C | STEP_MOTOR_D);
}
void STEP_MOTOR_4S(u8 speed) // 固定状态（制动）
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_C);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_B | STEP_MOTOR_D);
	delay_ms(speed);
	STEP_MOTOR_OFF();
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B | STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_C);	
	delay_ms(speed);
	STEP_MOTOR_OFF();
	delay_ms(speed);
	STEP_MOTOR_OFF();
}
// 4拍转动，速度快，力小
void STEP_MOTOR_4R(u8 speed)
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_B);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	delay_ms(speed);
	STEP_MOTOR_OFF();
}
void STEP_MOTOR_4L(u8 speed)
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_B);
	delay_ms(speed);
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	delay_ms(speed);
	STEP_MOTOR_OFF();
}
// 8拍转动，速度慢，力大
void STEP_MOTOR_8R(u8 speed)
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B|STEP_MOTOR_C|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_C|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_B);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_B | STEP_MOTOR_C);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B|STEP_MOTOR_A|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_B|STEP_MOTOR_C);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_D);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B|STEP_MOTOR_C);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	delay_ms(speed);
	
	STEP_MOTOR_OFF();
}
void STEP_MOTOR_8L(u8 speed)
{
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B|STEP_MOTOR_C|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C|STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_D);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_B|STEP_MOTOR_C);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_D);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_B);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_D);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_B|STEP_MOTOR_A|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_C | STEP_MOTOR_B);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_A|STEP_MOTOR_D|STEP_MOTOR_C);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_B);
	delay_ms(speed);
	
	GPIO_ResetBits(STEP_MOTOR_PORT,STEP_MOTOR_C|STEP_MOTOR_D);
	GPIO_SetBits(STEP_MOTOR_PORT,STEP_MOTOR_A | STEP_MOTOR_B);
	delay_ms(speed);
	STEP_MOTOR_OFF();
}